// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types';
import { RequestBuilder } from '../../http/transport/request-builder';
import { SerializationStyle } from '../../http/serialization/base-serializer';
import { LoLMastery, loLMasteryResponse } from '../common/lo-l-mastery';
import { GetLolMasteriesParams } from './request-params';

export class LoLMasteriesService extends BaseService {
  /**
   * List masteries
   * @param {FilterOverLoLMasteries} [filter] - Options to filter results. String fields are case sensitive <br/>For more information on filtering, see [docs](/docs/filtering-and-sorting#filter).
   * @param {RangeOverLoLMasteries} [range] - Options to select results within ranges <br/>For more information on ranges, see [docs](/docs/filtering-and-sorting#range).
   * @param {any[]} [sort] - Options to sort results <br/>For more information on sorting, see [docs](/docs/filtering-and-sorting#sort).
   * @param {SearchOverLoLMasteries} [search] - Options to search results <br/>For more information on searching, see [docs](/docs/filtering-and-sorting#search).
   * @param {Page} [page] - Pagination in the form of `page=2` or `page[size]=30&page[number]=2`
   * @param {number} [perPage] - Equivalent to `page[size]`
   * @returns {Promise<HttpResponse<LoLMastery[]>>} A list of League-of-Legends masteries
   */
  async getLolMasteries(
    params?: GetLolMasteriesParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<LoLMastery[]>> {
    const request = new RequestBuilder<LoLMastery[]>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/lol/masteries')
      .setRequestSchema(z.any())
      .setResponseSchema(z.array(loLMasteryResponse))
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'filter',
        value: params?.filter,
        style: SerializationStyle.DEEP_OBJECT,
      })
      .addQueryParam({
        key: 'range',
        value: params?.range,
        style: SerializationStyle.DEEP_OBJECT,
      })
      .addQueryParam({
        key: 'sort',
        value: params?.sort,
      })
      .addQueryParam({
        key: 'search',
        value: params?.search,
        style: SerializationStyle.DEEP_OBJECT,
      })
      .addQueryParam({
        key: 'page',
        value: params?.page,
      })
      .addQueryParam({
        key: 'per_page',
        value: params?.perPage,
      })
      .build();
    return this.client.call<LoLMastery[]>(request);
  }

  /**
   * Get a single mastery by ID
   * @param {number} lolMasteryId - A mastery ID
   * @returns {Promise<HttpResponse<LoLMastery>>} A League-of-Legends mastery
   */
  async getLolMasteriesLolMasteryId(
    lolMasteryId: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<LoLMastery>> {
    const request = new RequestBuilder<LoLMastery>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/lol/masteries/{lol_mastery_id}')
      .setRequestSchema(z.any())
      .setResponseSchema(loLMasteryResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'lol_mastery_id',
        value: lolMasteryId,
      })
      .build();
    return this.client.call<LoLMastery>(request);
  }
}
