// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const searchOverDota2Matches = z.lazy(() => {
  return z.object({
    matchType: z.string().optional(),
    name: z.string().optional(),
    slug: z
      .string()
      .min(1)
      .regex(/^[ a-zA-Z0-9_-]+$/)
      .optional(),
    status: z.string().optional(),
    winnerType: z.string().optional(),
  });
});

/**
 *
 * @typedef  {SearchOverDota2Matches} searchOverDota2Matches
 * @property {MatchType}
 * @property {string}
 * @property {string}
 * @property {MatchStatus}
 * @property {MatchWinnerType}
 */
export type SearchOverDota2Matches = z.infer<typeof searchOverDota2Matches>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverDota2MatchesResponse = z.lazy(() => {
  return z
    .object({
      match_type: z.string().optional(),
      name: z.string().optional(),
      slug: z
        .string()
        .min(1)
        .regex(/^[ a-zA-Z0-9_-]+$/)
        .optional(),
      status: z.string().optional(),
      winner_type: z.string().optional(),
    })
    .transform((data) => ({
      matchType: data['match_type'],
      name: data['name'],
      slug: data['slug'],
      status: data['status'],
      winnerType: data['winner_type'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverDota2MatchesRequest = z.lazy(() => {
  return z
    .object({
      matchType: z.string().nullish(),
      name: z.string().nullish(),
      slug: z.string().nullish(),
      status: z.string().nullish(),
      winnerType: z.string().nullish(),
    })
    .transform((data) => ({
      match_type: data['matchType'],
      name: data['name'],
      slug: data['slug'],
      status: data['status'],
      winner_type: data['winnerType'],
    }));
});
