// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum LoLDrakeType {
  CHEMTECH = 'chemtech',
  CLOUD = 'cloud',
  ELDER = 'elder',
  HEXTECH = 'hextech',
  INFERNAL = 'infernal',
  MOUNTAIN = 'mountain',
  OCEAN = 'ocean',
}
