// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const searchOverLoLTeamLastGames = z.lazy(() => {
  return z.object({
    status: z.string().optional(),
    winnerType: z.string().optional(),
  });
});

/**
 *
 * @typedef  {SearchOverLoLTeamLastGames} searchOverLoLTeamLastGames
 * @property {GameStatus} - The game status
 * @property {OpponentType}
 */
export type SearchOverLoLTeamLastGames = z.infer<typeof searchOverLoLTeamLastGames>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverLoLTeamLastGamesResponse = z.lazy(() => {
  return z
    .object({
      status: z.string().optional(),
      winner_type: z.string().optional(),
    })
    .transform((data) => ({
      status: data['status'],
      winnerType: data['winner_type'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverLoLTeamLastGamesRequest = z.lazy(() => {
  return z.object({ status: z.string().nullish(), winnerType: z.string().nullish() }).transform((data) => ({
    status: data['status'],
    winner_type: data['winnerType'],
  }));
});
