// This file was generated by liblab | https://liblab.com/

export type { FilterOverLoLMatches } from './filter-over-lo-l-matches';
export type { RangeOverLoLMatches } from './range-over-lo-l-matches';
export type { SearchOverLoLMatches } from './search-over-lo-l-matches';
export type { LoLMatch } from './lo-l-match';
export type { FilterOverLoLMatchesOpponentId } from './filter-over-lo-l-matches-opponent-id';
export type { FilterOverLoLMatchesVideogameTitle } from './filter-over-lo-l-matches-videogame-title';
export type { FilterOverLoLMatchesVideogameVersion } from './filter-over-lo-l-matches-videogame-version';
export type { LoLMatchGame } from './lo-l-match-game';
export type { LoLMatchPlayer } from './lo-l-match-player';
export type { LoLMatchVideogameTitle } from './lo-l-match-videogame-title';
export type { LoLMatchVideogameVersion } from './lo-l-match-videogame-version';
export type { LoLMatchWinner } from './lo-l-match-winner';
export type { LoLMatchWinnerId } from './lo-l-match-winner-id';
export type { LoLMatchGamePlayer } from './lo-l-match-game-player';
export { LoLMatchGameWinnerType } from './lo-l-match-game-winner-type';
export { LoLMatchGamePlayerRole } from './lo-l-match-game-player-role';
export { LoLMatchPlayerRole } from './lo-l-match-player-role';
export type { Winner1_5 } from './winner-1-5';
export type { Winner2_5 } from './winner-2-5';
