// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum OwMapGameMode {
  ASSAULT = 'Assault',
  CONTROL = 'Control',
  ESCORT = 'Escort',
  HYBRID = 'Hybrid',
  PUSH = 'Push',
}
