// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const shortTournamentWinnerType = z.enum(['Player', 'Team']);

export type ShortTournamentWinnerType = z.infer<typeof shortTournamentWinnerType>;
