// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const searchOverCsgoGames = z.lazy(() => {
  return z.object({
    status: z.string().optional(),
  });
});

/**
 *
 * @typedef  {SearchOverCsgoGames} searchOverCsgoGames
 * @property {GameStatus} - The game status
 */
export type SearchOverCsgoGames = z.infer<typeof searchOverCsgoGames>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverCsgoGamesResponse = z.lazy(() => {
  return z
    .object({
      status: z.string().optional(),
    })
    .transform((data) => ({
      status: data['status'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const searchOverCsgoGamesRequest = z.lazy(() => {
  return z.object({ status: z.string().nullish() }).transform((data) => ({
    status: data['status'],
  }));
});
