// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum ValorantPlayerShield {
  HEAVYSHIELD = 'heavy_shield',
  LIGHTSHIELD = 'light_shield',
  NOSHIELD = 'no_shield',
}
