// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const rangeOverStarcraft2Teams = z.lazy(() => {
  return z.object({
    acronym: z.array(z.string()).min(2).max(2).optional(),
    id: z.array(z.number()).min(2).max(2).optional(),
    location: z.array(z.string()).min(2).max(2).optional(),
    modifiedAt: z.array(z.string()).min(2).max(2).optional(),
    name: z.array(z.string()).min(2).max(2).optional(),
    slug: z.array(z.string()).min(2).max(2).optional(),
  });
});

/**
 *
 * @typedef  {RangeOverStarcraft2Teams} rangeOverStarcraft2Teams
 * @property {string[]}
 * @property {number[]}
 * @property {string[]}
 * @property {string[]}
 * @property {string[]}
 * @property {string[]}
 */
export type RangeOverStarcraft2Teams = z.infer<typeof rangeOverStarcraft2Teams>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const rangeOverStarcraft2TeamsResponse = z.lazy(() => {
  return z
    .object({
      acronym: z.array(z.string()).min(2).max(2).optional(),
      id: z.array(z.number()).min(2).max(2).optional(),
      location: z.array(z.string()).min(2).max(2).optional(),
      modified_at: z.array(z.string()).min(2).max(2).optional(),
      name: z.array(z.string()).min(2).max(2).optional(),
      slug: z.array(z.string()).min(2).max(2).optional(),
    })
    .transform((data) => ({
      acronym: data['acronym'],
      id: data['id'],
      location: data['location'],
      modifiedAt: data['modified_at'],
      name: data['name'],
      slug: data['slug'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const rangeOverStarcraft2TeamsRequest = z.lazy(() => {
  return z
    .object({
      acronym: z.array(z.string()).nullish(),
      id: z.array(z.number()).nullish(),
      location: z.array(z.string()).nullish(),
      modifiedAt: z.array(z.string()).nullish(),
      name: z.array(z.string()).nullish(),
      slug: z.array(z.string()).nullish(),
    })
    .transform((data) => ({
      acronym: data['acronym'],
      id: data['id'],
      location: data['location'],
      modified_at: data['modifiedAt'],
      name: data['name'],
      slug: data['slug'],
    }));
});
