// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const incidentDeletionReason = z.lazy(() => {
  return z.union([z.string(), z.string(), z.string()]);
});

/**
 *
 * @typedef  {IncidentDeletionReason} incidentDeletionReason
 * @property {string}
 * @property {string}
 * @property {IncidentDeletionReasonDeleted} - The entity no longer exists.
 */
export type IncidentDeletionReason = z.infer<typeof incidentDeletionReason>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const incidentDeletionReasonResponse = z.lazy(() => {
  return z.union([z.string(), z.string(), z.string()]);
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const incidentDeletionReasonRequest = z.lazy(() => {
  return z.union([z.string(), z.string(), z.string()]);
});
