// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum ValorantAbilityType {
  ABILITYONE = 'ability_one',
  ABILITYTWO = 'ability_two',
  GRENADEABILITY = 'grenade_ability',
  ULTIMATEABILITY = 'ultimate_ability',
}
